# Generated by Django 5.0.1 on 2024-01-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtemprecords',
            old_name='image',
            new_name='image_path',
        ),
    ]
