# Generated by Django 4.2.5 on 2023-10-17 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_camera_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="image",
        ),
    ]
