# Generated by Django 4.2.5 on 2023-10-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_criminals_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="image",
            field=models.ImageField(default="none", upload_to="camera_images/"),
        ),
    ]
