# Generated by Django 4.2.5 on 2023-10-22 23:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_camera_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encodings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criminal", models.CharField(max_length=150)),
                (
                    "encoding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
            ],
        ),
    ]
