# Generated by Django 4.2.5 on 2023-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_encodings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criminals",
            name="first_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="criminals",
            name="last_name",
            field=models.CharField(max_length=120),
        ),
    ]
