# Generated by Django 4.2.5 on 2023-10-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_criminals_first_name_alter_criminals_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encodings",
            name="criminal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.criminals"
            ),
        ),
    ]
