# Generated by Django 4.2.5 on 2023-10-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_encodings_criminal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
