# Generated by Django 4.2.5 on 2023-11-03 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_criminalsrecords"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CriminalsRecords",
        ),
    ]
