# Generated by Django 4.2.5 on 2023-11-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_delete_criminalsrecords"),
    ]

    operations = [
        migrations.CreateModel(
            name="CriminalsRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.FilePathField()),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                (
                    "criminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.criminals"
                    ),
                ),
            ],
        ),
    ]
