# Generated by Django 4.2.5 on 2023-11-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_camera_latitude_alter_camera_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalsrecords',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.camera'),
        ),
        migrations.AlterField(
            model_name='criminalsrecords',
            name='criminal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.criminals'),
        ),
        migrations.AlterField(
            model_name='criminalsrecords',
            name='image_path',
            field=models.FilePathField(path='/'),
        ),
    ]
