# Generated by Django 4.2.5 on 2023-11-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_criminalsrecords_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalsrecords',
            name='image_path',
            field=models.URLField(default='https://www.youtube.com'),
        ),
    ]
