# Generated by Django 4.2.5 on 2023-11-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_criminalsrecords_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.ImageField(default='none', upload_to='./media/cameras/'),
        ),
    ]
