# Generated by Django 4.2.5 on 2023-11-20 08:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_camera_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminals',
            name='image',
            field=models.ImageField(default=55, upload_to=api.models.criminal_image_path),
            preserve_default=False,
        ),
    ]
