# Generated by Django 4.2.5 on 2023-11-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_criminals_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encodings',
        ),
    ]
