# Generated by Django 5.0 on 2023-12-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_criminalsrecords_image_path_temprecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempClientLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
