# Generated by Django 5.0 on 2023-12-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_tempclientlocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempclientlocations',
            name='latitude',
            field=models.FloatField(unique=True),
        ),
        migrations.AlterField(
            model_name='tempclientlocations',
            name='longitude',
            field=models.FloatField(unique=True),
        ),
    ]
