# Generated by Django 5.0.1 on 2024-01-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_tempclientlocations_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
        ),
    ]
