# Generated by Django 5.0.1 on 2024-01-16 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_uniquekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTempRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.criminals')),
            ],
        ),
    ]
